### ISSUE TITLE
passband label in Photometry Results appears wrong

### ISSUE THREAD

**Issue by ijiraq** [CASTOR-telescope/ETC_frontend#4]
In the photometry results section, two of the entries are listed as 'u' (see image).  The 2nd one should be 'g'

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1132123/168189885-02f75f10-a75f-447a-b613-c9d4b4e2e032.png">

**Comment by BearBearCodes** [comment]
Argh! I was doing some slight refactoring before the full release and copied the line without changing the label. This will be a quick fix. Thanks for noticing!
